"""add_page_number_to_document_chunks

Revision ID: 71f4a2d8662f
Revises: 79f4d9a1c5d4
Create Date: 2026-02-25 22:24:32.496161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f4a2d8662f'
down_revision: Union[str, Sequence[str], None] = '79f4d9a1c5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.drop_index(op.f('document_chunks_embedding_idx'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_documents_file_key'), table_name='documents')
    op.create_unique_constraint(None, 'documents', ['file_key'])
    op.drop_index(op.f('ix_messages_user_session'), table_name='messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_user_session'), 'messages', ['user_id', 'session_id'], unique=False)
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_index(op.f('ix_documents_file_key'), 'documents', ['file_key'], unique=True)
    op.create_index(op.f('document_chunks_embedding_idx'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
