"""refactor_messages_to_json_blob

Revision ID: bbd142964e50
Revises: 71f4a2d8662f
Create Date: 2026-02-26 07:27:28.049112

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bbd142964e50"
down_revision: Union[str, Sequence[str], None] = "71f4a2d8662f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up old data: existing multi-row sessions would violate the new UNIQUE constraint.
    # We keep only the columns we need and drop the rest.
    op.execute("DELETE FROM messages")

    op.add_column(
        "messages",
        sa.Column("messages_json", sa.Text(), nullable=False, server_default="[]"),
    )
    op.add_column(
        "messages",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.text("NOW()")
        ),
    )
    op.drop_index(op.f("ix_messages_session_id"), table_name="messages")
    op.create_index(
        op.f("ix_messages_session_id"), "messages", ["session_id"], unique=True
    )
    op.drop_column("messages", "role")
    op.drop_column("messages", "content")
    op.drop_column("messages", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "messages",
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "messages", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_messages_session_id"), table_name="messages")
    op.create_index(
        op.f("ix_messages_session_id"), "messages", ["session_id"], unique=False
    )
    op.drop_column("messages", "updated_at")
    op.drop_column("messages", "messages_json")
    # ### end Alembic commands ###
